### ISSUE TITLE
Support testnet

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-sdk#113]

**Comment by tiero** [comment]
AFAIK, we need to support it in `Trade` class having one of the parameter be `testnet`?

**Comment by louisinger** [comment]
> AFAIK, we need to support it in `Trade` class having one of the parameter be `testnet`? @louisinger 

Where did u see this in Trade class ? Note that in buy/sell we can access the network type via the Identity class provided as a parameter.

**Comment by tiero** [comment]
https://github.com/tdex-network/tdex-sdk/blob/b82eac0135e61fef6111bf0bd17cb6dd41ce194c/src/core.ts#L3 but looks like is not used anywhere?

**Comment by louisinger** [comment]
Oh yeah, you're right. I think we can remove `chain` and `verbose` members? is verbose really useful (only referenced in swap file)

**Comment by tiero** [comment]
yes we can remove it if not used
